#spring:
#  datasource:
 #   url: dbc:postgresql://localhost:5432/mysqld?sslmode=disable
  #  username: 'postgres'
   # password: '12345'
    #driver-class-name: org.postgresql.Driver

 # jpa:
  #  hibernate:
   #   ddl-auto: update
    #show-sql: true
    #properties:
     # hibernate:
      #  dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mysqld
    initialization-mode: never

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: false

    show-sql: true


logging:
  level:
    ROOT: ERROR